name: 'Bye World'
description: 'Greet someone'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  random-number:
    description: "Random number"
  github-path:
    description: "Path of github action"
runs:
  using: 'docker'
  image: 'dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
    - ${{ github.action_path }}