name: 'Bye World'
description: 'Greet someone'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  random-number:
    description: "Random number"
  event-path:
    description: "Path of event"
  path:
    description: "Path on the runner to the file that sets variables"    
runs:
  using: 'docker'
  image: 'dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
    - ${{ github.event-path }}
    - ${{ github.path }}